# ==========================================
# Fichier de configuration de test WebServ
# ==========================================

server {
    # Premier serveur principal
    listen 8080 ;
    server_name localhost ;
    error_page 404 /errors/404.html ;
    client_max_body_size 1000000 ;

    # Route par defaut
    location / {
        root ./www ;
        index index.html ;
        autoindex off ;
        allow_methods GET POST DELETE;
    }

    # Route pour les fichiers statiques
    location /assets {
        root ./www ;
        autoindex on ;
        allow_methods GET ;
    }
}

# Deuxieme serveur virtuel sur un autre port
server {
    listen 9090 ;
    server_name webserv.local ;
    client_max_body_size 500 ;

    location / {
        root /var/www/second_site ;
        index default.html ;
        allow_methods GET POST DELETE ;
    }
}

server {
    listen 4242;
    server_name tasty;
    client_max_body_size 1000;
    
    location /assets {
        root /var/www/assets ;
        autoindex on ;
        allow_methods GET ;
    }
}
